### PR TITLE
Uploader: Log the filename too, if an upload fails. 

### LINKED ISSUE #292: Improve error output
Currently, it could sometimes be complicated to find out for which file the local schema check failed when doing a batch upload. We should add the filename to the error message.

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Resolves #292

### CODE REVIEW

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Comment by tschmidtb51** [comment]
LGTM and works.

**Review by bernhardreiter — APPROVED** [review]
LGTM

File: cmd/csaf_uploader/main.go [hunk 1]
```diff
@@ -435,6 +435,8 @@ func main() {
 	}
 
 	for _, arg := range args {
-		check(p.process(arg))
+		if err := p.process(arg); err != nil {
```
Comment (bernhardreiter) [inline cmd/csaf_uploader/main.go:438]: This changes the semantics a bit, because `check()` will use os.exit(0) in some cases, the new code doesn't. @s-l-teichmann is this intentional?

**Review by bernhardreiter — CHANGES_REQUESTED** [review]

File: cmd/csaf_uploader/main.go (hunk 1 above)
Comment (s-l-teichmann) [reply cmd/csaf_uploader/main.go:438]: `check`  only does `os.exit(0)` if the command line help was written. This case does not apply here. All errors come from the processing.

**Review by bernhardreiter — APPROVED** [review]
LGTM
