### PR TITLE
fix: engine is invalid when name is missing

### LINKED ISSUE #709: Engine validation fails when version is empty
Hi, I am facing an issue and I am not sure if it is me not using the library correctly or if this is an issue.

I am parsing a document that contains the following value for `document.tracking.generator`:

```json
{
  "document": {
    ... 
    "tracking": {
      "current_release_date": "2025-12-04T10:14:56Z",
      "generator": {
        "date": "2025-12-04T10:14:56Z",
        "engine": {
          "name": "pyCSAF"
        }
      },
      ...
  },
```

The Go struct for [engine](https://github.com/gocsaf/csaf/blob/main/csaf/advisory.go#L267) has 
```
Version *string `json:"version,omitempty"`
```
which seems matching [the spec](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf_json_schema.json) which states that only the name is required 👇 

```json
"engine": {
	"title": "Engine of document generation",
    "description": "Contains information about the engine that generated the CSAF document.",
    "type": "object",
    "required": [
    	"name"
    ],
    ...
} 
```

But the `Validate` [function](https://github.com/gocsaf/csaf/blob/main/csaf/advisory.go#L894) returns an error when the version is `nil`.

When running the validate command, the csaf file appears to be valid, so I was leanning toward a bug. The `Validate` should not return an error when the version is nil.

### PR DESCRIPTION
**Pull request by benja-M-1**
Hello 👋 , this PR fixes https://github.com/gocsaf/csaf/issues/709

According to the [specification](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf_json_schema.json), the validation of the `tracking.generator.engine` should check the name is not nil rather than the version which is optional. This is what the PR changes.

### CODE REVIEW

File: csaf/advisory.go [hunk 1]
```diff
@@ -891,8 +891,8 @@ func (rs Revisions) Validate() error {
 
 // Validate validates an Engine.
 func (e *Engine) Validate() error {
-	if e.Version == nil {
-		return errors.New("'version' is missing")
+	if e.Name == nil {
```
Comment (bernhardreiter) [inline csaf/advisory.go:894]: I wonder if this is necessary, as the schema validation we do, should catch a missing name. So maybe the function can be removed altogether?

Comment (benja-M-1) [reply csaf/advisory.go:894]: That works for me! Doing it

Comment (benja-M-1) [reply csaf/advisory.go:894]: However, when creating an Advisory "manually" and calling the Validate function on it, there are no checks (that's how I spotted the problem), same when calling the `LoadAdvisory` function.

Comment (benja-M-1) [reply csaf/advisory.go:894]: And I am thinking, that's a backward compatibility break. The function is exposed, which means if someone uses it then their code will break when updating the next version of the lib. 
Are you still sure you want to remove if? :)

Comment (bernhardreiter) [reply csaf/advisory.go:894]: > sure you want to remove if?

No, just thinking aloud.

>  that's a backward compatibility break.

We could empty the function, so the API stays the same.  

Removing the wrong check is a fix, so we could do a patch release.

Comment (bernhardreiter) [reply csaf/advisory.go:894]: > there are no checks

Does the schema validation catch the missing name in that situations? That would be "a check", wouldn't it?

Comment (benja-M-1) [reply csaf/advisory.go:894]: I tested with the main branch, not the branch with the fix.

>   * /document/tracking/generator/engine: missing property 'name'

That's the output when the name is missing. 

>   * /document/tracking/generator/engine/name: minLength: got 0, want 1
 
And that's the output when the name is empty.

When the version is missing it does not fail as it does when loading a file.

Comment (bernhardreiter) [reply csaf/advisory.go:894]: > When the version is missing it does not fail as it does when loading a file.

What do you mean in particular? It would be okay, if it does not fail, I think.

Comment (benja-M-1) [reply csaf/advisory.go:894]: Sorry I wasn't very clear. What I meant is:
- `go run ./cmd/csaf_validator/main.go` does not fail, which is 👍 
- `csaf.LoadAdvisory(path)` does fail and the changes I propose fixe it

**Comment by bernhardreiter** [comment]
> go run ./cmd/csaf_validator/main.go does not fail, which is 👍

But doesn't this mean that it does not call Validate() and probably should? *confused*
Guess I'll have a look at some tests or @s-l-teichmann tomorrow.

**Comment by benja-M-1** [comment]
> But doesn't this mean that it does not call Validate() and probably should? confused

No, the validator commad uses the jsonschema to validate. They don't use the same code.

**Review by bernhardreiter — APPROVED** [review]
LGTM

**Review by s-l-teichmann — APPROVED** [review]
LGTM & works

**Review by s-l-teichmann — APPROVED** [review]
LGTM
